import LeanEthCS.Forks.Altair.Inherited
import LeanEthCS.Forks.Altair.Sync
import LeanEthCS.Forks.Altair.LightClient
import LeanEthCS.Forks.Altair.Block
import LeanEthCS.Forks.Altair.State

/-!
# `LeanEthCS.Forks.Bellatrix.Inherited`: explicit consensus-spec container inheritance

Re-binds every container that Bellatrix inherits unchanged from earlier forks (Phase0, Altair) into the `LeanEthCS.Forks.Bellatrix` namespace via `abbrev`. With these aliases in place every `LeanEthCS.Forks.Bellatrix.<Container>` reference resolves uniformly, the dispatcher in `Cli/Main.lean` (and any other caller) is freed from having to know which earlier fork originally defined the type.

The `abbrev` form is `@[reducible]` by default, so SSZRepr instance synthesis transparently sees through every alias to the underlying `deriving SSZRepr` instance attached to the originating fork's definition. No new instances are minted, no extra trust commitments.

Grouping is by *original* source fork (the fork that actually defines the type), so this file doubles as a hand-readable ledger of `Bellatrix`'s consensus-spec lineage.

AUTO-GENERATED by `scripts/gen_cli_dispatch.py`. Do not edit.
Regenerate via `just gen-cli-dispatch`.
-/

set_option autoImplicit false

namespace LeanEthCS.Forks.Bellatrix

/-! ### Inherited from Phase0 -/

abbrev BeaconBlockHeader := LeanEthCS.Forks.Phase0.BeaconBlockHeader
abbrev Validator := LeanEthCS.Forks.Phase0.Validator
abbrev Fork := LeanEthCS.Forks.Phase0.Fork
abbrev Checkpoint := LeanEthCS.Forks.Phase0.Checkpoint
abbrev AttestationData := LeanEthCS.Forks.Phase0.AttestationData
abbrev DepositMessage := LeanEthCS.Forks.Phase0.DepositMessage
abbrev DepositData := LeanEthCS.Forks.Phase0.DepositData
abbrev VoluntaryExit := LeanEthCS.Forks.Phase0.VoluntaryExit
abbrev SignedVoluntaryExit := LeanEthCS.Forks.Phase0.SignedVoluntaryExit
abbrev SignedBeaconBlockHeader := LeanEthCS.Forks.Phase0.SignedBeaconBlockHeader
abbrev ProposerSlashing := LeanEthCS.Forks.Phase0.ProposerSlashing
abbrev Eth1Data := LeanEthCS.Forks.Phase0.Eth1Data
abbrev ForkData := LeanEthCS.Forks.Phase0.ForkData
abbrev SigningData := LeanEthCS.Forks.Phase0.SigningData
abbrev Eth1Block := LeanEthCS.Forks.Phase0.Eth1Block
abbrev IndexedAttestation := LeanEthCS.Forks.Phase0.IndexedAttestation
abbrev PendingAttestation := LeanEthCS.Forks.Phase0.PendingAttestation
abbrev Attestation := LeanEthCS.Forks.Phase0.Attestation
abbrev AttesterSlashing := LeanEthCS.Forks.Phase0.AttesterSlashing
abbrev Deposit := LeanEthCS.Forks.Phase0.Deposit
abbrev AggregateAndProof := LeanEthCS.Forks.Phase0.AggregateAndProof
abbrev SignedAggregateAndProof := LeanEthCS.Forks.Phase0.SignedAggregateAndProof

namespace HistoricalBatch
  abbrev Minimal := LeanEthCS.Forks.Phase0.HistoricalBatch.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Phase0.HistoricalBatch.Mainnet
end HistoricalBatch

/-! ### Inherited from Altair -/

abbrev SyncCommitteeMessage := LeanEthCS.Forks.Altair.SyncCommitteeMessage
abbrev SyncAggregatorSelectionData := LeanEthCS.Forks.Altair.SyncAggregatorSelectionData
abbrev LightClientHeader := LeanEthCS.Forks.Altair.LightClientHeader

namespace SyncAggregate
  abbrev Minimal := LeanEthCS.Forks.Altair.SyncAggregate.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.SyncAggregate.Mainnet
end SyncAggregate

namespace SyncCommittee
  abbrev Minimal := LeanEthCS.Forks.Altair.SyncCommittee.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.SyncCommittee.Mainnet
end SyncCommittee

namespace SyncCommitteeContribution
  abbrev Minimal := LeanEthCS.Forks.Altair.SyncCommitteeContribution.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.SyncCommitteeContribution.Mainnet
end SyncCommitteeContribution

namespace ContributionAndProof
  abbrev Minimal := LeanEthCS.Forks.Altair.ContributionAndProof.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.ContributionAndProof.Mainnet
end ContributionAndProof

namespace SignedContributionAndProof
  abbrev Minimal := LeanEthCS.Forks.Altair.SignedContributionAndProof.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.SignedContributionAndProof.Mainnet
end SignedContributionAndProof

namespace LightClientBootstrap
  abbrev Minimal := LeanEthCS.Forks.Altair.LightClientBootstrap.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.LightClientBootstrap.Mainnet
end LightClientBootstrap

namespace LightClientUpdate
  abbrev Minimal := LeanEthCS.Forks.Altair.LightClientUpdate.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.LightClientUpdate.Mainnet
end LightClientUpdate

namespace LightClientFinalityUpdate
  abbrev Minimal := LeanEthCS.Forks.Altair.LightClientFinalityUpdate.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.LightClientFinalityUpdate.Mainnet
end LightClientFinalityUpdate

namespace LightClientOptimisticUpdate
  abbrev Minimal := LeanEthCS.Forks.Altair.LightClientOptimisticUpdate.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.LightClientOptimisticUpdate.Mainnet
end LightClientOptimisticUpdate

end LeanEthCS.Forks.Bellatrix
