import LeanEthCS.Forks.Deneb.Inherited
import LeanEthCS.Forks.Deneb.Primitives
import LeanEthCS.Forks.Deneb.Execution
import LeanEthCS.Forks.Deneb.Block
import LeanEthCS.Forks.Deneb.State
import LeanEthCS.Forks.Deneb.Blob
import LeanEthCS.Forks.Deneb.LightClient

/-!
# `LeanEthCS.Forks.Electra.Inherited`: explicit consensus-spec container inheritance

Re-binds every container that Electra inherits unchanged from earlier forks (Phase0, Altair, Bellatrix, Capella, Deneb) into the `LeanEthCS.Forks.Electra` namespace via `abbrev`. With these aliases in place every `LeanEthCS.Forks.Electra.<Container>` reference resolves uniformly, the dispatcher in `Cli/Main.lean` (and any other caller) is freed from having to know which earlier fork originally defined the type.

The `abbrev` form is `@[reducible]` by default, so SSZRepr instance synthesis transparently sees through every alias to the underlying `deriving SSZRepr` instance attached to the originating fork's definition. No new instances are minted, no extra trust commitments.

Grouping is by *original* source fork (the fork that actually defines the type), so this file doubles as a hand-readable ledger of `Electra`'s consensus-spec lineage.

AUTO-GENERATED by `scripts/gen_cli_dispatch.py`, do not edit.
Regenerate via `just gen-cli-dispatch`.
-/

set_option autoImplicit false

namespace LeanEthCS.Forks.Electra

/-! ### Inherited from Phase0 -/

abbrev BeaconBlockHeader := LeanEthCS.Forks.Phase0.BeaconBlockHeader
abbrev Validator := LeanEthCS.Forks.Phase0.Validator
abbrev Fork := LeanEthCS.Forks.Phase0.Fork
abbrev Checkpoint := LeanEthCS.Forks.Phase0.Checkpoint
abbrev AttestationData := LeanEthCS.Forks.Phase0.AttestationData
abbrev DepositMessage := LeanEthCS.Forks.Phase0.DepositMessage
abbrev DepositData := LeanEthCS.Forks.Phase0.DepositData
abbrev VoluntaryExit := LeanEthCS.Forks.Phase0.VoluntaryExit
abbrev SignedVoluntaryExit := LeanEthCS.Forks.Phase0.SignedVoluntaryExit
abbrev SignedBeaconBlockHeader := LeanEthCS.Forks.Phase0.SignedBeaconBlockHeader
abbrev ProposerSlashing := LeanEthCS.Forks.Phase0.ProposerSlashing
abbrev Eth1Data := LeanEthCS.Forks.Phase0.Eth1Data
abbrev ForkData := LeanEthCS.Forks.Phase0.ForkData
abbrev SigningData := LeanEthCS.Forks.Phase0.SigningData
abbrev Eth1Block := LeanEthCS.Forks.Phase0.Eth1Block
abbrev PendingAttestation := LeanEthCS.Forks.Phase0.PendingAttestation
abbrev Deposit := LeanEthCS.Forks.Phase0.Deposit

namespace HistoricalBatch
  abbrev Minimal := LeanEthCS.Forks.Phase0.HistoricalBatch.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Phase0.HistoricalBatch.Mainnet
end HistoricalBatch

/-! ### Inherited from Altair -/

abbrev SyncCommitteeMessage := LeanEthCS.Forks.Altair.SyncCommitteeMessage
abbrev SyncAggregatorSelectionData := LeanEthCS.Forks.Altair.SyncAggregatorSelectionData

namespace SyncAggregate
  abbrev Minimal := LeanEthCS.Forks.Altair.SyncAggregate.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.SyncAggregate.Mainnet
end SyncAggregate

namespace SyncCommittee
  abbrev Minimal := LeanEthCS.Forks.Altair.SyncCommittee.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.SyncCommittee.Mainnet
end SyncCommittee

namespace SyncCommitteeContribution
  abbrev Minimal := LeanEthCS.Forks.Altair.SyncCommitteeContribution.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.SyncCommitteeContribution.Mainnet
end SyncCommitteeContribution

namespace ContributionAndProof
  abbrev Minimal := LeanEthCS.Forks.Altair.ContributionAndProof.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.ContributionAndProof.Mainnet
end ContributionAndProof

namespace SignedContributionAndProof
  abbrev Minimal := LeanEthCS.Forks.Altair.SignedContributionAndProof.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.SignedContributionAndProof.Mainnet
end SignedContributionAndProof

/-! ### Inherited from Bellatrix -/

abbrev PowBlock := LeanEthCS.Forks.Bellatrix.PowBlock

/-! ### Inherited from Capella -/

abbrev Withdrawal := LeanEthCS.Forks.Capella.Withdrawal
abbrev BLSToExecutionChange := LeanEthCS.Forks.Capella.BLSToExecutionChange
abbrev SignedBLSToExecutionChange := LeanEthCS.Forks.Capella.SignedBLSToExecutionChange
abbrev HistoricalSummary := LeanEthCS.Forks.Capella.HistoricalSummary

/-! ### Inherited from Deneb -/

abbrev BlobIdentifier := LeanEthCS.Forks.Deneb.BlobIdentifier
abbrev ExecutionPayloadHeader := LeanEthCS.Forks.Deneb.ExecutionPayloadHeader

namespace ExecutionPayload
  abbrev Minimal := LeanEthCS.Forks.Deneb.ExecutionPayload.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Deneb.ExecutionPayload.Mainnet
end ExecutionPayload

namespace BlobSidecar
  abbrev Minimal := LeanEthCS.Forks.Deneb.BlobSidecar.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Deneb.BlobSidecar.Mainnet
end BlobSidecar

end LeanEthCS.Forks.Electra
