import LeanEthCS.Forks.Capella.Inherited
import LeanEthCS.Forks.Capella.Withdrawal
import LeanEthCS.Forks.Capella.Execution
import LeanEthCS.Forks.Capella.LightClient
import LeanEthCS.Forks.Capella.Block
import LeanEthCS.Forks.Capella.State

/-!
# `LeanEthCS.Forks.Deneb.Inherited`: explicit consensus-spec container inheritance

Re-binds every container that Deneb inherits unchanged from earlier forks (Phase0, Altair, Bellatrix, Capella) into the `LeanEthCS.Forks.Deneb` namespace via `abbrev`. With these aliases in place every `LeanEthCS.Forks.Deneb.<Container>` reference resolves uniformly, the dispatcher in `Cli/Main.lean` (and any other caller) is freed from having to know which earlier fork originally defined the type.

The `abbrev` form is `@[reducible]` by default, so SSZRepr instance synthesis transparently sees through every alias to the underlying `deriving SSZRepr` instance attached to the originating fork's definition. No new instances are minted, no extra trust commitments.

Grouping is by *original* source fork (the fork that actually defines the type), so this file doubles as a hand-readable ledger of `Deneb`'s consensus-spec lineage.

AUTO-GENERATED by `scripts/gen_cli_dispatch.py`, do not edit.
Regenerate via `just gen-cli-dispatch`.
-/

set_option autoImplicit false

namespace LeanEthCS.Forks.Deneb

/-! ### Inherited from Phase0 -/

abbrev BeaconBlockHeader := LeanEthCS.Forks.Phase0.BeaconBlockHeader
abbrev Validator := LeanEthCS.Forks.Phase0.Validator
abbrev Fork := LeanEthCS.Forks.Phase0.Fork
abbrev Checkpoint := LeanEthCS.Forks.Phase0.Checkpoint
abbrev AttestationData := LeanEthCS.Forks.Phase0.AttestationData
abbrev DepositMessage := LeanEthCS.Forks.Phase0.DepositMessage
abbrev DepositData := LeanEthCS.Forks.Phase0.DepositData
abbrev VoluntaryExit := LeanEthCS.Forks.Phase0.VoluntaryExit
abbrev SignedVoluntaryExit := LeanEthCS.Forks.Phase0.SignedVoluntaryExit
abbrev SignedBeaconBlockHeader := LeanEthCS.Forks.Phase0.SignedBeaconBlockHeader
abbrev ProposerSlashing := LeanEthCS.Forks.Phase0.ProposerSlashing
abbrev Eth1Data := LeanEthCS.Forks.Phase0.Eth1Data
abbrev ForkData := LeanEthCS.Forks.Phase0.ForkData
abbrev SigningData := LeanEthCS.Forks.Phase0.SigningData
abbrev Eth1Block := LeanEthCS.Forks.Phase0.Eth1Block
abbrev IndexedAttestation := LeanEthCS.Forks.Phase0.IndexedAttestation
abbrev PendingAttestation := LeanEthCS.Forks.Phase0.PendingAttestation
abbrev Attestation := LeanEthCS.Forks.Phase0.Attestation
abbrev AttesterSlashing := LeanEthCS.Forks.Phase0.AttesterSlashing
abbrev Deposit := LeanEthCS.Forks.Phase0.Deposit
abbrev AggregateAndProof := LeanEthCS.Forks.Phase0.AggregateAndProof
abbrev SignedAggregateAndProof := LeanEthCS.Forks.Phase0.SignedAggregateAndProof

namespace HistoricalBatch
  abbrev Minimal := LeanEthCS.Forks.Phase0.HistoricalBatch.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Phase0.HistoricalBatch.Mainnet
end HistoricalBatch

/-! ### Inherited from Altair -/

abbrev SyncCommitteeMessage := LeanEthCS.Forks.Altair.SyncCommitteeMessage
abbrev SyncAggregatorSelectionData := LeanEthCS.Forks.Altair.SyncAggregatorSelectionData

namespace SyncAggregate
  abbrev Minimal := LeanEthCS.Forks.Altair.SyncAggregate.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.SyncAggregate.Mainnet
end SyncAggregate

namespace SyncCommittee
  abbrev Minimal := LeanEthCS.Forks.Altair.SyncCommittee.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.SyncCommittee.Mainnet
end SyncCommittee

namespace SyncCommitteeContribution
  abbrev Minimal := LeanEthCS.Forks.Altair.SyncCommitteeContribution.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.SyncCommitteeContribution.Mainnet
end SyncCommitteeContribution

namespace ContributionAndProof
  abbrev Minimal := LeanEthCS.Forks.Altair.ContributionAndProof.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.ContributionAndProof.Mainnet
end ContributionAndProof

namespace SignedContributionAndProof
  abbrev Minimal := LeanEthCS.Forks.Altair.SignedContributionAndProof.Minimal
  abbrev Mainnet := LeanEthCS.Forks.Altair.SignedContributionAndProof.Mainnet
end SignedContributionAndProof

/-! ### Inherited from Bellatrix -/

abbrev PowBlock := LeanEthCS.Forks.Bellatrix.PowBlock

/-! ### Inherited from Capella -/

abbrev Withdrawal := LeanEthCS.Forks.Capella.Withdrawal
abbrev BLSToExecutionChange := LeanEthCS.Forks.Capella.BLSToExecutionChange
abbrev SignedBLSToExecutionChange := LeanEthCS.Forks.Capella.SignedBLSToExecutionChange
abbrev HistoricalSummary := LeanEthCS.Forks.Capella.HistoricalSummary

end LeanEthCS.Forks.Deneb
